<?php

declare(strict_types=1);

namespace App\ValueObjects\Egypt;

use Carbon\Carbon;
use InvalidArgumentException;

/**
 * Company-level quarterly ETA Form 4 withholding report.
 *
 * One instance covers all employees for one quarter.
 * Immutable — generated by EtaForm4Service and handed directly to the API response.
 */
final readonly class EtaForm4Report
{
    private const QUARTER_MONTHS = [
        1 => [1, 2, 3],
        2 => [4, 5, 6],
        3 => [7, 8, 9],
        4 => [10, 11, 12],
    ];

    /** Due-date offsets: last day of the first month after the quarter ends. */
    private const QUARTER_DUE = [
        1 => '04-30',  // April 30
        2 => '07-31',  // July 31
        3 => '10-31',  // October 31
        4 => '01-31',  // January 31 next year
    ];

    /**
     * @param EtaForm4EmployeeRecord[] $employees
     */
    public function __construct(
        public int    $year,
        public int    $quarter,
        public string $periodLabel,
        public array  $employees,
        public float  $totalQuarterlyGross,
        public float  $totalQuarterlyTaxWithheld,
        public float  $totalEmployeeCount,
    ) {
        if ($quarter < 1 || $quarter > 4) {
            throw new InvalidArgumentException("Quarter must be 1–4, got {$quarter}.");
        }
    }

    public function dueDate(): Carbon
    {
        $suffix = self::QUARTER_DUE[$this->quarter];

        // Q4 is due in January of the NEXT year
        $dueYear = $this->quarter === 4 ? $this->year + 1 : $this->year;

        return Carbon::parse("{$dueYear}-{$suffix}");
    }

    /** Returns the three calendar month numbers that make up this quarter. */
    public function months(): array
    {
        return self::QUARTER_MONTHS[$this->quarter];
    }

    public function toArray(): array
    {
        return [
            'year'                          => $this->year,
            'quarter'                       => $this->quarter,
            'period_label'                  => $this->periodLabel,
            'months'                        => $this->months(),
            'due_date'                      => $this->dueDate()->toDateString(),
            'total_employee_count'          => $this->totalEmployeeCount,
            'total_quarterly_gross'         => $this->totalQuarterlyGross,
            'total_quarterly_tax_withheld'  => $this->totalQuarterlyTaxWithheld,
            'employees'                     => array_map(
                fn(EtaForm4EmployeeRecord $r) => $r->toArray(),
                $this->employees,
            ),
        ];
    }
}
